// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3DF3ByDQX-bqCsEhZwVD4NtnwdFZYgS4',
    appId: '1:1030906931559:web:db039d12db6b3aa0a1a7c2',
    messagingSenderId: '1030906931559',
    projectId: 'projectambw',
    authDomain: 'projectambw.firebaseapp.com',
    storageBucket: 'projectambw.appspot.com',
    measurementId: 'G-VWB9SQ2H8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4yvozLczFvbhwWigrbF52uCDCfgykTCQ',
    appId: '1:1030906931559:android:9df06293b2ad653ca1a7c2',
    messagingSenderId: '1030906931559',
    projectId: 'projectambw',
    storageBucket: 'projectambw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa3y2mPwpukKA58AgE40cRnV9XgHA3fSU',
    appId: '1:1030906931559:ios:030d4d1031cdd2b9a1a7c2',
    messagingSenderId: '1030906931559',
    projectId: 'projectambw',
    storageBucket: 'projectambw.appspot.com',
    iosClientId: '1030906931559-bdeuv8mip55bqgptndut422c5g19te7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
